config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  

  root 'welcome#index'

  get 'welcome/index'
  get '/about' => 'welcome#about', as: :about
  get '/feedback' => 'welcome#new_feedback', as: :new_feedback
  post '/feedback' => 'welcome#create_feedback', as: :create_feedback

  resources :news
  resources :blogs

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  resourcify
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :news
  belongs_to :blog
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3 }
  validates :email, presence: true, format: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/
  validates :body, presence: true
end

app/models/news.rb
class News < ActiveRecord::Base
  resourcify
  has_many :comments
end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Доступ обмежений."
    redirect_to root_url
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  load_and_authorize_resource

  def index
    @blogs = Blog.order(created_at: :desc)
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    blog = Blog.new(blog_params)
    if blog.save
      redirect_to blog
    else
      flash[:danger] = 'Something was wrong'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.destroy
      flash[:success] = 'Блог успішно видалено'
      redirect_to blogs_path
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :html)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  load_and_authorize_resource

  def index
    @news = News.order(created_at: :desc)
  end

  def show
    @news = News.find(params[:id])
  end

  def edit
  end

  def destroy
    @post = News.find(params[:id])
    if @post.destroy
      flash[:info] = 'Новину успішно видалено'
      redirect_to news_index_path
    end
  end

  def new
  end

  def create
    news = News.create(news_params)
    if news.save
      redirect_to news
    else
      flash[:danger] = "Something was wrong"
      redirect_to '/'
    end
  end

  private
  def news_params
    params.require(:news).permit(:title, :html)
  end
end

app/controllers/news_controller_controller.rb
class NewsControllerController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @last_blog = Blog.last
    @news = News.order(created_at: :desc).limit(2)
  end

  def about

  end

  def new_feedback
    @feedback = Feedback.new
  end

  def create_feedback
    feedback = Feedback.new(feedback_params)
    if feedback.save
      redirect_to '/'
    else
      redirect_to '/feedback'
    end
  end

  private
  def feedback_params
    params.require(:feedback).permit(:name, :email, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/index.html.erb
<h1> Блог </h1>
<% @blogs.each do |blog| %>

  <div class="col-lg-5">
    <h2> <%= blog.title %></h2>

    <p> <%= strip_tags blog.html.html_safe.truncate(200) %> </p>
      <span class="text-muted"> <%= blog.created_at %></span>
    <%= link_to 'Більше...', blog, class: 'pull-right' %>
  </div>

<% end %>
<% if can? :create, Blog %>
  <p><%= link_to "Новий блог", new_blog_path, class: 'btn btn-primary' %></p>
<% end %>

app/views/blogs/new.html.erb
<%= simple_form_for @blog do |f| %>
  <%= f.input :title, label: 'Заголовок' %>
  <%= f.input :html,label: 'Контент', as: :wysihtml5,:input_html => { :rows => 15 , :style => 'width: 100%'}%>
  <%= f.button :submit %>
<% end %>

app/views/blogs/show.html.erb
<div class="container">
  <h1> <%= @blog.title %> </h1>
  <p> <%= @blog.html.html_safe %></p>
  <% if can? :destroy, Blog %>
</br> <%= link_to 'Видалити', @blog, :confirm => 'Are you sure?',
          :method => :delete %>
  <% end %>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Max</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="jumbotron">

    <h1>John Lennon</h1>
    <p>Присягаю на вірність народу України.</p>

  </div>

  <%= nav_bar responsive: true do %>
    <%= menu_group do %>

        <%= menu_item "Головна", root_path %>
        <%= menu_item "Про мене", about_path%>
        <%= menu_item "Новини", news_index_path %>
        <%= menu_item "Блог", blogs_path %>

        <%= menu_item "Зворотній зв'язок", '/feedback'%>
        <%= menu_item "Партія 'Самопоміч'", 'http://samopomich.zt.ua/', target: '_blank' %>
        <%= menu_item "Facebook" %>
        <%= menu_item "Twitter" %>

    <% end %>
    <%= menu_group pull: :right do %>

      <% if user_signed_in? %>
        <%= drop_down current_user.email do %>
          <%= menu_item 'Налаштування', edit_user_registration_path %>
          <%= menu_item 'Вийти', destroy_user_session_path, :method=>'delete' %>
        <% end %>
      <% else %>
        <%= menu_item 'Увійти', new_user_session_path %>
        <%= menu_item 'Реєстрація', new_user_registration_path %>
      <% end %>




    <% end %>
  <% end %>
</div>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>



<footer class="footer">
  <div class="container">
    <p class="text-muted"> SiniiNet production. (c) 2015</p>
  </div>
</footer>

</body>
</html>

app/views/news/destroy.html.erb
<h1>News#destroy</h1>
<p>Find me in app/views/news/destroy.html.erb</p>

app/views/news/edit.html.erb
<h1>News#edit</h1>
<p>Find me in app/views/news/edit.html.erb</p>

app/views/news/index.html.erb
  <h1 class="title"> Новини </h3>

  <% @news.each do |news|%>
      <div class="col-lg-5">


        <p>
          <%= image_tag news.picture_url, width: 135, height: 100, class: 'leftimg' %>
          <%= link_to news.title, news %> </br>

            <span class="text-muted"> <%= news.created_at %> </span></br>
          <%= strip_tags news.html.html_safe.truncate(200) %>
          <%= link_to 'Читати далі...', news, class: 'pull-right' %>
        </p>
      </br>
      </div>

  <% end %>

  <% if can? :create, News %>
    <%= link_to "Створити новину", new_news_path, class: 'btn btn-primary' %>
  <% end %>

app/views/news/new.html.erb
<%= simple_form_for @news do |f| %>
  <%= f.input :title, label: 'Заголовок' %>
  <%= f.input :html,label: 'Контент', as: :wysihtml5,:input_html => { :rows => 15 , :style => 'width: 100%'}%>
  <%= f.button :submit %>
<% end %>

app/views/news/show.html.erb
<div class="span10">
  <h1> <%= @news.title %> </h1>
  <%= image_tag @news.picture_url, class: 'leftimg news_img' %>

  <p> <%= @news.html.html_safe %></p>
    <p class="text-muted"> <%= @news.created_at %></p>

  <% if can? :destroy, News %>
</br> <%= link_to 'Видалити', @news, :confirm => 'Are you sure?',
          :method => :delete %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="container-info">

  <div class="row">

    <div class="col-md-6">
      <h3 class="title"> Новини </h3>
      <% @news.each do |news|%>
          <div class="row">


            <p>
              <%= image_tag news.picture_url, width: 135, height: 100, class: 'leftimg' %>
              <%= link_to news.title, news %>
              <span class="text-muted" ><%= news.created_at %> </span> <br>
              <%= strip_tags news.html.html_safe.truncate(200) %>

            </p>

          </div>
      <% end %>
      <div class="pull-right">
        <%= link_to "Інші новини", controller: 'news', action: 'index'%>
      </div>
    </div>
    <div class="col-md-5">
      <h3 class="title"> Блог </h3>

      <div class="blog">
        <h4> <%= link_to @last_blog.title, @last_blog %></h4>
        <p>
          <%= strip_tags @last_blog.html.html_safe.truncate(550) %>

          <div class="pull-right">
            <%= link_to "Читати далі", @last_blog %>
          </div>
        </p>
      </div>

    </div>

  </div>
  <div class="row">
    <h3 align="center"> Фото </h3>
    <div id="owl-demo" class="gallery">

      <% Photo.all.each do |photo| %>
        <div class="item"> <%= image_tag photo.src, width: 350, height: 250%></div>
      <% end %>


    </div>
  </div>
<script>
$(document).ready(function() {

    $("#owl-demo").owlCarousel({

        autoPlay: 3000, //Set AutoPlay to 3 seconds

        items : 4,
        itemsDesktop : [1199,3],
        itemsDesktopSmall : [979,3]

    });

});
</script>
</div>

app/views/welcome/new_feedback.html.erb
<%= simple_form_for @feedback, url: create_feedback_path do |f|%>
  <%= f.input :name, placeholder: 'John Lennon', label: 'Ваше ім\'я'%>
  <%= f.input :email, placeholder: 'johny2@beatles.com', label: 'Ваша email адреса' %>
  <%= f.input :body, label: 'Текст повідомлення' %>
  <%= f.button :submit%>
<% end %>